# Copyright Louis Royer and the NextMN contributors. All rights reserved.
# Use of this source code is governed by a MIT-style license that can be
# found in the LICENSE file.
# SPDX-License-Identifier: MIT
name: "nextmn-testbed-pull-images"
services:
  mongo:
    image: docker.io/library/mongo
  postgres:
    image: docker.io/library/postgres
  nginx:
    image: docker.io/library/nginx
  base-irit:
    image: docker.io/louisroyer/base-irit
    build: https://github.com/louisroyer-docker/base-irit.git#master:.
  ue:
    image: docker.io/louisroyer/ueransim-ue
    build: https://github.com/louisroyer-docker/ueransim.git#master:ue
  gnb:
    image: docker.io/louisroyer/ueransim-gnb
    build: https://github.com/louisroyer-docker/ueransim.git#master:gnb
  debug:
    image: docker.io/louisroyer/network-debug
    build: https://github.com/louisroyer-docker/network-debug.git#master:network-debug
  free5gc-populate:
    image: docker.io/louisroyer/free5gc-populate
    build: https://github.com/louisroyer-docker/free5gc-populate.git#master:free5gc-populate
  dev-free5gc-populate:
    image: docker.io/louisroyer/dev-free5gc-populate
    build: https://github.com/louisroyer-docker/free5gc-populate.git#master:dev-free5gc-populate
  docker-setup:
    image: docker.io/louisroyer/docker-setup
    build: https://github.com/louisroyer-docker/docker-setup.git#master:.
  free5gc-upf:
    image: docker.io/louisroyer/dev-free5gc-upf
    build: https://github.com/louisroyer-docker/free5gc.git#master:upf
  nextmn-upf:
    image: docker.io/louisroyer/dev-nextmn-upf
    build: https://github.com/louisroyer-docker/nextmn.git#master:upf
  nextmn-srv6:
    image: ghcr.io/nextmn/srv6:0.0.27
    build:
      context: https://github.com/nextmn/srv6.git#v0.0.27
      args:
        SOURCE_DATE_EPOCH: 0
        BUILDKIT_CONTEXT_KEEP_GIT_DIR: true
  nextmn-srv6-ctrl:
    image: ghcr.io/nextmn/srv6-ctrl:0.0.25
    build:
      context: https://github.com/nextmn/srv6-ctrl.git#v0.0.25
      args:
        SOURCE_DATE_EPOCH: 0
        BUILDKIT_CONTEXT_KEEP_GIT_DIR: true
  nextmn-ue-lite:
    image: ghcr.io/nextmn/ue-lite:0.2.0
    build:
      context: https://github.com/nextmn/ue-lite.git#v0.2.0
      args:
        SOURCE_DATE_EPOCH: 0
        BUILDKIT_CONTEXT_KEEP_GIT_DIR: true
  nextmn-gnb-lite:
    image: ghcr.io/nextmn/gnb-lite:0.1.0
    build:
      context: https://github.com/nextmn/gnb-lite.git#v0.1.0
      args:
        SOURCE_DATE_EPOCH: 0
        BUILDKIT_CONTEXT_KEEP_GIT_DIR: true
  nextmn-cp-lite:
    image: ghcr.io/nextmn/cp-lite:0.1.0
    build:
      context: https://github.com/nextmn/cp-lite.git#v0.1.0
      args:
        SOURCE_DATE_EPOCH: 0
        BUILDKIT_CONTEXT_KEEP_GIT_DIR: true
  amf:
    image: docker.io/louisroyer/dev-free5gc-amf
    build: https://github.com/louisroyer-docker/free5gc.git#master:amf
  ausf:
    image: docker.io/louisroyer/dev-free5gc-ausf
    build: https://github.com/louisroyer-docker/free5gc.git#master:ausf
  chf:
    image: docker.io/louisroyer/dev-free5gc-chf
    build: https://github.com/louisroyer-docker/free5gc.git#master:chf
  nrf:
    image: docker.io/louisroyer/dev-free5gc-nrf
    build: https://github.com/louisroyer-docker/free5gc.git#master:nrf
  nssf:
    image: docker.io/louisroyer/dev-free5gc-nssf
    build: https://github.com/louisroyer-docker/free5gc.git#master:nssf
  pcf:
    image: docker.io/louisroyer/dev-free5gc-pcf
    build: https://github.com/louisroyer-docker/free5gc.git#master:pcf
  smf:
    image: docker.io/louisroyer/dev-free5gc-smf
    build: https://github.com/louisroyer-docker/free5gc.git#master:smf
  udm:
    image: docker.io/louisroyer/dev-free5gc-udm
    build: https://github.com/louisroyer-docker/free5gc.git#master:udm
  udr:
    image: docker.io/louisroyer/dev-free5gc-udr
    build: https://github.com/louisroyer-docker/free5gc.git#master:udr
  webconsole:
    image: docker.io/louisroyer/dev-free5gc-webconsole
    build: https://github.com/louisroyer-docker/free5gc.git#master:webconsole
